#+startup: show2levels
#+html: <div><a href="https://github.com/rennsax/dotfiles/actions/workflows/test-install.yml"><img alt="GitHub Actions Workflow Status" src="https://img.shields.io/github/actions/workflow/status/rennsax/dotfiles/test-install.yml?label=Test"></a> <img alt="GitHub Release" src="https://img.shields.io/github/v/release/rennsax/dotfiles"></div>

* dotfiles

My personal dotfiles. Managed with Nix Flake.

** Installation

Currently my dotfiles are adapted for three kinds of OSes: NixOS, macOS and
Ubuntu. The configurations are divided into two parts: system-wide and
user-wide. You can install these two parts individually.

Before installation, at least make sure you've installed =git=, =curl= and
=make=. If you are on Ubunut, =./scripts/init-ubuntu= can help you do that.

Install system-wide configuration:

#+begin_src sh
# Depending on which OS you are on.
make init-nixos
make init-darwin
make init-ubuntu
#+end_src

Install user-wide configuration:

#+begin_src sh
make init-home
#+end_src

Or, if you only want to install Nix as a package manager:

#+begin_src sh
make install-nix
#+end_src

which utilizes the [[https://github.com/DeterminateSystems/nix-installer][nix-installer from DeterminateSystems]].

NOTE:

- ~make init-home~ only affects user-level configurations. Therefore, it even
  does not require "sudo", as long as you have correctly installed Nix. As a
  result, it won't change the user's default shell which needs to touch the
  system file ~/etc/passwd~. You may manually set the default with chsh(1). This
  fact matters when you want to install my dotfiles on Ubuntu.

** See Also

- [[https://github.com/rennsax/init.lua][rennsax/init.lua: My neovim configuration.]] (I do not use Neovim anymore, hence
  it may be obsolete.)
- [[https://github.com/rennsax/.emacs.d][rennsax/.emacs.d: My Emacs configuration. 🍓]]

** References

- [[https://wiki.archlinux.org/title/XDG_Base_Directory][XDG Base Directory - ArchWiki]]
- [[https://www.ecb.torontomu.ca/guides/zsh-intro.pdf][zsh-intro.pdf]]
- [[https://thevaluable.dev/zsh-install-configure-mouseless/][Configuring Zsh Without Dependencies]]
- [[https://zdharma-continuum.github.io/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html][Zsh Plugin Standard]]
- [[https://github.com/ryan4yin/nix-config][ryan4yin/nix-config]]
- [[https://determinate.systems/posts/nix-direnv/][Determinate Systems: Effortless dev environments with Nix and direnv]]
