#!/usr/bin/env bash

# Description: mv files into the macOS native trashbin
#
# Dependencies:
#   - macos-trash - https://github.com/sindresorhus/macos-trash
#   - OR trash - https://hasseg.org/trash/
#
# Shell: Bash
# Authors: @rennsax

set -e

if ! command -v trash >/dev/null; then
    printf "trash cli for macOS not found\n" >&2
    exit 2
fi

TRASH_CMD="command trash"

ask-confirm() {
    printf "Will trash the following files:\n"
    printf -- '- %s\n' "$@"

    while true; do
        read -r -p "[Y/n] " yn
        case "$yn" in
            [Yy]* )
                return 0 ;;
            [Nn]* )
                return 1 ;;
            * )
                printf "Please answer yes or no.\n" >&2 ;;
        esac
    done
}

trash-selected() {
    selection="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection"
    if [ ! -s "$selection" ]; then
        printf "No selected files\n" >&2
        exit 1
    fi
    IFS= readarray -d '' selected_files < "$selection"

    if ask-confirm "${selected_files[@]}"; then
        $TRASH_CMD "${selected_files[@]}"
        # Clear selection
        [ -p "$NNN_PIPE" ] && printf "-" > "$NNN_PIPE"
    fi
}

trash-hovered() {
    test -e "$1"
    ask-confirm "$1" && $TRASH_CMD "$1"
}

# Or use select builtin
printf "Trash which files?\n"
select choice in "selected" "hovered"; do
    case $choice in
        selected )
            trash-selected; break ;;
        hovered )
            trash-hovered "$2/$1"; break ;;
    esac
done
