#!/usr/bin/env bash

#
# Patch the hostname and username according to your current system.
#
# This script patches the "impure" part of this Nix flake, which should be
# dynamic on different systems, especially for those who uses Nix as a package
# manager alongside the system's default one.
#
# To eliminate the annoying warning "Git tree '...' is dirty" from Nix flake
# commands, you can tell git to “assume” they are unchanged by:
#
#  > git update-index --assume-unchanged vars/*
#

set -e

sed -i "s|rennsax|$(id -un)|" ./vars/me.nix
sed -i "s|/path/to/your/nix/config|$PWD|" ./vars/default.nix
