#!/usr/bin/env zsh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

yabai_log() {
    str_format=$1
    shift
    printf "[%s] $str_format" "$(date +'%F %T')" $@
}

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          on             \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m config --space 5 layout float

# add some apps that you don't want yabai to manage
unmanaged_apps=(
    '^System Settings$'
    '^Terminal$'
    '^Photos$'
    '^Reminders$'
    '^Tencent Lemon$'
    '^App Store$'
    '^Finder$'
    '^Mail$'
    '^Font Book$'
    '^Rocket$'
    '^TextEdit$'
    '^VMware Fusion$'
    '^jBox$'
    '^Activity Monitor$'
    '^Archive Utility$'
    '^BetterTouchTool$'
)
space5_apps=(
    '^Clash Verge$'
    '^WeChat$'
    '^Telegram$'
    '^Jitsi Meet$'
    '^不背单词$'
    '^TencentMeeting$'
)
for app in ${unmanaged_apps}; do
    yabai -m rule --add app=${app} manage=off
done
for app in ${space5_apps}; do
    yabai -m rule --add app=${app} space=^5 manage=off
done
yabai -m rule --add app='^Arc$' title='^Rennsax$' manage=off

focus_under_cursor() {
    if yabai -m query --windows --space |
        jq -er 'map(select(.["has-focus"] == true)) | length == 0' &>/dev/null; then
        yabai -m window --focus mouse 2>/dev/null || true
    fi
}

yabai -m signal --add event=window_destroyed \
    action="${functions[focus_under_cursor]}" active=yes
yabai -m signal --add event=application_terminated \
    action="${functions[focus_under_cursor]}" active=yes
yabai -m signal --add event=space_changed \
    action="${functions[focus_under_cursor]}" active=yes

borders active_color=0xffff7c5c width=10.0 inactive_color=0xff494d64 width=5.0 &

yabai_log "configuration loaded.."
