on:
  pull_request:
  push:
    branches:
      - main
      - test-workflow

jobs:
  install-lab-server:
    name: Test installation for lab server
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - run: make init-ubuntu
      env:
        INSTALL_DEBIAN_NO_SJTU_SOURCES: 1
        INSTALL_DEBIAN_TRACE: 1

    - run: |
        nix shell nixpkgs#home-manager -c \
          home-manager --impure switch --flake .#ipads-server.renbj

  build-workstation-iso:
    name: Test building the ISO image for lab workstation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - run: |
        nix build .#nixosConfigurations.ipads-nixos.config.system.build.images.iso
