name: Monthly Upgrade
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 28 * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Get current month
        run: |
          echo "CURRENT_MONTH=$(date +'%B')" >> $GITHUB_ENV
          echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Monthly Flake Upgrade (${{ env.CURRENT_MONTH }}, ${{ env.CURRENT_YEAR }})"
          pr-labels: |
            dependencies
            automated
