on:
  pull_request:
  push:
    branches:
      - main
      - test-workflow

jobs:
  lints:
    name: Test Installation
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - run: make init-ubuntu
      env:
        INSTALL_DEBIAN_NO_SJTU_SOURCES: 1
        INSTALL_DEBIAN_TRACE: 1

    - run: make init-home HOME_VARIANT=minimal
