name: Test installation scripts on Ubuntu
on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests
        run: |
          ./scripts/install.sh
        env:
          INSTALL_DEBIAN_TRACE: 1
          INSTALL_DEBIAN_NO_SJTU_SOURCES: 1

      - name: Link dotfiles
        run: |
          ./scripts/init-dotfiles.sh

      # "link dotfiles" should be idempotent
      - name: Link dotfiles twice
        run: |
          ./scripts/init-dotfiles.sh
